server {
    listen 80;
    server_name hitscord.site www.hitscord.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hitscord.site www.hitscord.site;

    ssl_certificate     /etc/letsencrypt/live/hitscord.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hitscord.site/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://hitscord:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/wss {
        proxy_pass http://hitscord:80;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}