server {
    listen 80;
    server_name server_name 166664.msk.web.highserver.ru;
    return 301 https://$host$request_uri;

    location ~ /\.env {
        deny all;
    }
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 443 ssl;
    server_name 166664.msk.web.highserver.ru;
    ssl_certificate /etc/letsencrypt/live/166664.msk.web.highserver.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/166664.msk.web.highserver.ru/privkey.pem;

    client_max_body_size 10M;
    root /usr/share/nginx/html;
    index index.html;

    location /api/wss {
        proxy_pass http://hitscord:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location /api/ {
        proxy_pass http://hitscord:80/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        if ($request_method = OPTIONS) {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type' always;
            return 204;
        }

        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
