const base = "https://196673.msk.web.highserver.ru/api/admin";
const routers = {
    login: `${base}/login`,
    logout: `${base}/logout`,
    users: `${base}/users/list`,
    rolesShort: `${base}/roles/list/short`,
    addRole: `${base}/roles/add`,
    removeRole: `${base}/roles/remove`,
    getChannels: `${base}/deletedChannels/list`,
    rewiveChannel: `${base}/deletedChannels/rewive`,
    rolesFull: `${base}/roles/list/full`,
    roleCreate: `${base}/roles/create`,
    roleUpdate: `${base}/roles/rename`,
    roleDelete: `${base}/roles/delete`,
    icon: `${base}/icon`,
    operations: `${base}/operations/list`,
    changePassword: `${base}/user/change/password`,
    register: `${base}/registration`,
    serverList: `${base}/server/list`,
    serverInfo: `${base}/server/info`,
    createUser: `${base}/user/create`,
    changeUserIcon: `${base}/user/icon/change`,
    deleteUserIcon: `${base}/user/icon/delete`,
    changeUserData: `${base}/user/profile/change`,
    deleteUser: `${base}/user/delete`,
};
export default routers;